### ISSUE TITLE
Simulink model

### ISSUE THREAD

**Issue by tianlaihuiyin** [aniket0112/exoskeleton#2]
Can you save a Simulink model for a low version (2016a)?

**Comment by parmarbhavik** [comment]
It is created in 2016a only.
Can you specify what kind of problem you are facing?

**Comment by tianlaihuiyin** [comment]
I can not open the Simulink model by matlab2016a

**Comment by parmarbhavik** [comment]
Please send me a screenshot of error message you are getting in matlab.

**Comment by tianlaihuiyin** [comment]
I have solved it, thank you！
