### ISSUE TITLE
ADAMS-MATLAB cosimulation folder

### ISSUE THREAD

**Issue by aniket0112** [aniket0112/exoskeleton#3]
Does the repository need ADAMS MATLAB cosimulation folder? If not then please remove it and push a new commit. The working model is in load analysis folder I guess. @parmarbhavik

**Comment by parmarbhavik** [comment]
Working ADAMS model is same in both the folder.Purpose of this repo was just for designing of contoller on no load.
It is of no use further.

**Comment by aniket0112** [comment]
@parmarbhavik  cool, then when you push with the new exported model then delete this folder also so that there is no confusion!

**Comment by tianlaihuiyin** [comment]
I can't open the.bin file directly in Adams software, and my Adams software is version 2017. The wrong message is“ERROR: The database conversion file" aview20170200.dct "was not found.
Please check the aview.pth file and file protections.”

**Comment by parmarbhavik** [comment]
Your current version of ADAMS may be 2017.1
Update it to 2017.2 to eliminate the problem

**Comment by tianlaihuiyin** [comment]
Yes, 2017.2  is valid, thank you very much!

**Comment by tianlaihuiyin** [comment]
ADAMS 2017.2 and Matlab 2016a Co-Simulation error：“Error reported by S-function 'adams_plant' in 'computedTorquePD/adams_sub/ADAMS Plant/S-Function':
Error in Adams(server) simulation startup.  AEI_Initialize: Error in initialization.”  and There are no "adams_plant.dll"  files in the Adams file.

**Comment by parmarbhavik** [comment]
https://in.mathworks.com/matlabcentral/answers/740-how-to-fix-error-in-simulink-adams-co-simulation-could-not-connect-to-adams-server
Just have a look at this to solve the initialization problem!!
